services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=2G
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,EXTERNAL://localhost:19092
      - --rpc-addr=0.0.0.0:33145
      - --advertise-rpc-addr=redpanda:33145
      - --pandaproxy-addr=0.0.0.0:8082
      - --advertise-pandaproxy-addr=redpanda:8082
    ports:
      - "8081:8081"   # Schema registry port
      - "19092:19092" # external proxy
      - "8082:8082"   # Pandaproxy (opcional, REST)
      - "9092:9092"   # Kafka API
      - "9644:9644"   # Admin API
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8080:8080"     # UI web
    environment:
      - KAFKA_BROKERS=redpanda:9092
    depends_on:
      - redpanda
    volumes:
      - ./console-config.yml:/etc/console/config.yml:ro

volumes:
  redpanda-data:
